services:
  db:
    image: postgres
    container_name: postgres.local
    hostname: db
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
  app:
    container_name: app.local
    build:
      dockerfile: ./dev.Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./:/rails
